# Generated by Django 5.1.1 on 2024-09-29 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_election_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 29, 17, 13, 9, 829321, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='evidence',
            field=models.FileField(default=datetime.datetime(2024, 9, 29, 17, 13, 23, 153834, tzinfo=datetime.timezone.utc), upload_to='evidence/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
